name: Publish Navitia Documentation

on:
  pull_request:
  push:
    branches:
      - dev
      - release


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install bundle
      run: apt update && apt install -y bundler
    - name: git checkout on dev
      run: git checkout dev
    - name: generate documentation on dev
      working-directory: documentation/slate 
      run: |
        bundle install
        bundle exec middleman build
        rm -fr /tmp/job_documentation_publish_slate
        mkdir -p /tmp/job_documentation_publish_slate
        mv build /tmp/job_documentation_publish_slate
    - name: move new documentation on gh-pages
      run: |
        rm -f documentation/slate/Gemfile.lock
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages
        rm -fr *
        mv /tmp/job_documentation_publish_slate/build/* .
    - name: update action user and commit changes
      env:
        DEPLOY_KEY: ${{ secrets.ACTION_SECRET_KEY }}
      run: |
        git config --global user.email "tech.navitia.development@kisio.com"
        git config --global user.name "Action"
        git commit -m "Add changes" -a
        git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
        
        eval `ssh-agent -t 60 -s`
        echo "$DEPLOY_KEY" | ssh-add -
          
        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
          
        git push
        ssh-agent -k
