name: Publish Navitia Documentation

on:
  pull_request:
  push:
    branches:
      - dev
      - release


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: navitia/debian8_dev

    steps:
    - uses: actions/checkout@v1
    - name: install bundle
      run: apt update && apt install -y bundler
    - name: git checkout on dev
      run: git checkout dev
    - name: generate documentation on dev
      working-directory: documentation/slate 
      run: |
        bundle exec middleman build
        rm -fr /tmp/job_documentation_publish_slate
        mkdir -p /tmp/job_documentation_publish_slate
        mv build /tmp/job_documentation_publish_slate
    - name: move new documentation on gh-pages
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages
