name: Publish Navitia Documentation

on:
  pull_request:
  push:
    branches:
      - dev
      - release


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: navitia/debian8_dev

    steps:
    - uses: actions/checkout@v1
    - name: install bundle
      run: apt update && apt install -y bundler
    - name: git checkout on dev
      run: git checkout dev
