name: CI

on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types:
      - created


jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            docker_image: [navitia/debian8_dev]

    container:
        image: ${{matrix.docker_image}}

    services:
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v1
    - name: get submodule
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
    - name: Install dependencies
      run: pip install -r source/jormungandr/requirements_dev.txt
    - name: configure
      run: cmake source
    - name: make
      run:  make -j $(nproc)
    - name: tests
      run: |
        export JORMUNGANDR_BROKER_URL='amqp://guest:guest@rabbitmq:5672//'
        export KRAKEN_RABBITMQ_HOST='rabbitmq'
        ctest --output-on-failure
    - name: remove useless tests
      run: |
        rm -rf tests/mock_kraken kraken/tests ed/tests fare/tests routing/tests calendar/tests
        rm -rf georef/tests proximity_list/tests time_tables/tests equipment/tests
        rm -rf ptreferential/tests
    - name: install tyr dependencies
      run: |
        pip install -r source/tyr/requirements_dev.txt
        pip install -r source/sql/requirements.txt
      env:
        NAVITIA_DOCKER_NETWORK: ${{ job.container.network }}
        TYR_CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'


