name: CI

on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types:
      - created


jobs:

  check_artemis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check artemis
      run: ./source/scripts/checkJenkinsJob.sh Artemis
    - name: check artemis IDFM
      run: ./source/scripts/checkJenkinsJob.sh Artemis_idfm


  artemisNG:
    runs-on: ubuntu-latest
    steps:
      - name: clone ArtemisNG
        uses: actions/checkout@master
        with:
          repository: CanalTP/artemis.git
          path: 'artemisNG'
      - name: clone navitia-docker-compose
        uses: actions/checkout@master
        with:
          repository: CanalTP/navitia-docker-compose.git
          path: 'docker-compose'    
      - name: install requirements
        run: cd $GITHUB_WORKSPACE/artemisNG/artemis && mkvirtualenv -p python3 -r requirements.txt

      - name: get Navitia docker containers
        run: |
          cd $GITHUB_WORKSPACE/docker-compose
          TAG=dev docker-compose pull


